services:
  - type: worker
    name: wordseek-bot
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    preDeployCommand: bun run db:migrate
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URI
        sync: false
      - key: DAILY_WORDLE_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERS
        sync: false
      - key: UPDATES_CHANNEL
        sync: false
      - key: DISCUSSION_GROUP
        sync: false
